import { translate as __ } from 'foremanReact/common/I18n';

export const TASKS_DASHBOARD_AVAILABLE_SEARCH_QUERY_TYPES = {
  RUNNING: 'RUNNING',
  PAUSED: 'PAUSED',
  STOPPED: 'STOPPED',
  SCHEDULED: 'SCHEDULED',
  LAST: 'LAST',
  OVER: 'OVER',
  ERROR: 'ERROR',
  WARNING: 'WARNING',
  SUCCESS: 'SUCCESS',
};

export const TASKS_DASHBOARD_AVAILABLE_TIME_PERIODS = {
  H24: 'H24',
  H12: 'H12',
  WEEK: 'WEEK',
};

export const TASKS_DASHBOARD_AVAILABLE_TIME_PERIODS_TEXT = {
  [TASKS_DASHBOARD_AVAILABLE_TIME_PERIODS.H24]: __('24h'),
  [TASKS_DASHBOARD_AVAILABLE_TIME_PERIODS.H12]: __('12h'),
  [TASKS_DASHBOARD_AVAILABLE_TIME_PERIODS.WEEK]: __('week'),
};

export const FOREMAN_TASKS_DASHBOARD_UPDATE_SEARCH_QUERY =
  'FOREMAN_TASKS_DASHBOARD_UPDATE_SEARCH_QUERY';

export const FOREMAN_TASKS_DASHBOARD_UPDATE_TIME_PERIOD =
  'FOREMAN_TASKS_DASHBOARD_UPDATE_TIME_PERIOD';
