# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: TreatCommentsAsGroupSeparators, Include.
# Include: **/*.gemspec
Gemspec/OrderedDependencies:
  Exclude:
    - 'foreman-tasks.gemspec'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: final_newline, final_blank_line
Layout/TrailingEmptyLines:
  Exclude:
    - 'locale/action_names.rb'

# Offense count: 1
Lint/EmptyWhen:
  Exclude:
    - 'app/lib/actions/proxy_action.rb'
# Cop supports --auto-correct.
Lint/SendWithMixinArgument:
  Exclude:
    - 'lib/foreman_tasks/engine.rb'
    - 'lib/foreman_tasks/test_extensions.rb'
    - 'test/unit/actions/action_with_sub_plans_test.rb'

# Offense count: 1
Lint/UselessAssignment:
  Exclude:
    - 'lib/foreman_tasks/tasks/export_tasks.rake'

# Offense count: 3
# Configuration parameters: EnforcedStyleForLeadingUnderscores.
# SupportedStylesForLeadingUnderscores: disallowed, required, optional
Naming/MemoizedInstanceVariableName:
  Exclude:
    - 'app/controllers/foreman_tasks/recurring_logics_controller.rb'
    - 'app/lib/actions/recurring_action.rb'
    - 'lib/foreman_tasks_core/otp_manager.rb'

# Offense count: 11
# Configuration parameters: MinNameLength, AllowNamesEndingInNumbers, AllowedNames, ForbiddenNames.
# AllowedNames: io, id, to, by, on, in, at, ip, db, os, pp
Naming/MethodParameterName:
  Exclude:
    - 'app/helpers/foreman_tasks/foreman_tasks_helper.rb'

# Offense count: 1
# Configuration parameters: NamePrefix, ForbiddenPrefixes, AllowedMethods, MethodDefinitionMacros.
# NamePrefix: is_, has_, have_
# ForbiddenPrefixes: is_, has_, have_
# AllowedMethods: is_a?
# MethodDefinitionMacros: define_method, define_singleton_method
Naming/PredicateName:
  Exclude:
    - 'spec/**/*'
    - 'app/models/foreman_tasks/task/status_explicator.rb'

Rails/ActiveRecordAliases:
  Exclude:
    - 'app/models/foreman_tasks/task/dynflow_task.rb'
    - 'test/factories/task_factory.rb'

# Offense count: 6
# Configuration parameters: Include.
# Include: db/migrate/*.rb
Rails/CreateTableWithTimestamps:
  Exclude:
    - 'db/migrate/20131205204140_create_foreman_tasks.rb'
    - 'db/migrate/20131209122644_create_foreman_tasks_locks.rb'
    - 'db/migrate/20150907124936_create_recurring_logic.rb'
    - 'db/migrate/20150907131503_create_task_groups.rb'
    - 'db/migrate/20151112152108_create_triggerings.rb'

# Offense count: 1
# SupportedStyles: numeric, symbolic
Rails/HttpStatus:
  Exclude:
    - 'app/controllers/foreman_tasks/concerns/hosts_controller_extension.rb'
# Offense count: 1
# Configuration parameters: Include.
# Include: app/**/*.rb, config/**/*.rb, db/**/*.rb, lib/**/*.rb
Rails/Output:
  Exclude:
    - 'lib/foreman_tasks/cleaner.rb'

# Offense count: 5
Rails/OutputSafety:
  Exclude:
    - 'app/helpers/foreman_tasks/foreman_tasks_helper.rb'

# Offense count: 1
# Configuration parameters: Include.
# Include: **/Rakefile, **/*.rake
Rails/RakeEnvironment:
  Exclude:
    - 'lib/foreman_tasks/tasks/test.rake'

# Offense count: 12
# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, EnforcedStyle.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  Exclude:
    - 'app/lib/actions/action_with_sub_plans.rb'
    - 'app/models/foreman_tasks/task/dynflow_task.rb'
    - 'app/models/foreman_tasks/task/status_explicator.rb'
    - 'app/models/foreman_tasks/task/summarizer.rb'
    - 'app/models/foreman_tasks/task/task_cancelled_exception.rb'
    - 'app/models/setting/foreman_tasks.rb'
    - 'lib/foreman_tasks/dynflow/configuration.rb'
    - 'lib/foreman_tasks/dynflow/console_authorizer.rb'
    - 'lib/foreman_tasks/dynflow/persistence.rb'
    - 'test/controllers/api/recurring_logics_controller_test.rb'
    - 'test/controllers/api/tasks_controller_test.rb'

# Offense count: 2
Style/DoubleNegation:
  Exclude:
    - 'app/models/foreman_tasks/lock.rb'
    - 'app/models/foreman_tasks/recurring_logic.rb'

# Offense count: 2
# Cop supports --auto-correct.
Style/Encoding:
  Exclude:
    - 'foreman-tasks-core.gemspec'
    - 'foreman-tasks.gemspec'

# Offense count: 6
# Cop supports --auto-correct.
Style/ExpandPathArguments:
  Exclude:
    - 'foreman-tasks-core.gemspec'
    - 'foreman-tasks.gemspec'
    - 'lib/foreman_tasks/engine.rb'
    - 'script/rails'

# Offense count: 36
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

# Configuration parameters: AllowMultipleReturnValues.
Style/RedundantReturn:
  Exclude:
    - 'app/lib/actions/helpers/humanizer.rb'
    - 'app/models/foreman_tasks/concerns/action_triggering.rb'
    - 'lib/foreman_tasks/dynflow/console_authorizer.rb'
