# TODO: remove this file by either moving cops here or fixing code
inherit_from:
  - .rubocop_todo.yml

AllCops:
  Include:
    - 'Rakefile'
    - 'app/views/foreman_tasks/api/**/*.rabl'
    - lib/**/*.rake

Rails:
  Enabled: true

# KWargs are not present in actionpack < 5
Rails/HttpPositionalArguments:
  Enabled: false

# Don't enforce documentation
Style/Documentation:
  Enabled: false

# Support both ruby19 and hash_rockets
Style/HashSyntax:
  Enabled: false
