require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'locale/*'

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Rails:
  Enabled: true

# Don't prefer is_a? over kind_of?
Style/ClassCheck:
  Enabled: false

# Don't enforce documentation
Style/Documentation:
  Enabled: false

# Support both ruby19 and hash_rockets
Style/HashSyntax:
  Enabled: false

# Both double and single quotes are OK
Style/StringLiterals:
  Enabled: false

# Don't enforce frozen string literals
Style/FrozenStringLiteralComment:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/FormatString:
  Enabled: false

Rails/Present:
  Exclude:
    - lib/foreman_tasks_core/**/*

Rails/FilePath:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false

Metrics:
  Enabled: false

Layout/LineLength:
  Enabled: false

Naming/FileName:
  Exclude:
    - '*.gemspec'
    - Gemfile
    - db/seeds.d/*
    - lib/foreman-tasks.rb

Layout/HeredocIndentation:
  Exclude:
    - '*.gemspec'
    - bin/*

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Performance/RegexpMatch:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Style/WordArray:
  Enabled: false
