export const FOREMAN_TASK_DETAILS_INIT = 'FOREMAN_TASK_DETAILS_INIT';

export const FOREMAN_TASK_DETAILS_FETCH_TASK_REQUEST =
  'FOREMAN_TASK_DETAILS_FETCH_TASK_REQUEST';
export const FOREMAN_TASK_DETAILS_FETCH_TASK_SUCCESS =
  'FOREMAN_TASK_DETAILS_FETCH_TASK_SUCCESS';
export const FOREMAN_TASK_DETAILS_FETCH_TASK_FAILURE =
  'FOREMAN_TASK_DETAILS_FETCH_TASK_FAILURE';

export const FOREMAN_TASK_DETAILS_STOP_POLLING =
  'FOREMAN_TASK_DETAILS_STOP_POLLING';
export const FOREMAN_TASK_DETAILS_START_POLLING =
  'FOREMAN_TASK_DETAILS_START_POLLING';
