export const FOREMAN_TASK_DETAILS_TOGGLE_UNLOCK_MODAL =
  'FOREMAN_TASK_DETAILS_TOGGLE_UNLOCK_MODAL';
export const FOREMAN_TASK_DETAILS_TOGGLE_FORCE_UNLOCK_MODAL =
  'FOREMAN_TASK_DETAILS_TOGGLE_FORCE_UNLOCK_MODAL';
