export const UNLOCK_MODAL = 'unlockModal';
export const FORCE_UNLOCK_MODAL = 'forceUnlockModal';

export const TASKS_RESUME_REQUEST = 'TASKS_RESUME_REQUEST';
export const TASKS_RESUME_SUCCESS = 'TASKS_RESUME_SUCCESS';
export const TASKS_RESUME_FAILURE = 'TASKS_RESUME_FAILURE';
export const TASKS_CANCEL_REQUEST = 'TASKS_CANCEL_REQUEST';
export const TASKS_CANCEL_SUCCESS = 'TASKS_CANCEL_SUCCESS';
export const TASKS_CANCEL_FAILURE = 'TASKS_CANCEL_FAILURE';
